server:
  port: 12346

spring:
  application:
    name: ERIC-NFVO-EOCA-SECURITY
#    name: ERIC-NFVO-EOCA-RESOURCE

eureka:
  instance:
    prefer-ip-address: true
    preferIpAddress: true
  client:
    serviceUrl:
#      defaultZone: http://172.16.23.197:9010/eureka/
      defaultZone: http://localhost:18761/eureka/